env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends: ["htmlacademy/es6", "plugin:react/recommended"]

parser:
  babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ["react"]

settings:
  react:
    version: "16"

rules:
  object-curly-spacing: [1, "always", { "arraysInObjects": false, "objectsInObjects": false }]
